name: Build Cython Package for Multiple Python Versions

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.PYTHON_VERSION }}
      uses: actions/setup-python@v5

    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: ${{ matrix.PYTHON_VERSION }}  # 构建指定版本的wheels
        CIBW_SKIP: "cp27-* cp35-* cp36-*"  # 跳过不需要构建的版本
        CIBW_BEFORE_BUILD: "python -m pip install cython"  # 构建前安装Cython

    - name: Upload wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-${{ matrix.PYTHON_VERSION }}-${{ matrix.os }}
        path: wheelhouse/*.whl

  collect_wheels:
    needs: build_wheels
    name: Collect wheels and upload to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: wheels/
    - name: Upload to PyPI
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload --non-interactive --skip-existing wheels/*